apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../base
#namePrefix: staging-

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["/avalanchego/build/avalanchego", "--network-id=mainnet" ]
  target:
    kind: Deployment
    name: avalanche-deployment
    version: v1
