apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-deployment
  labels:
    app: avalanche
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avalanche
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: avalanche
        image: kerezov/avalanche:1
        command: ["/avalanchego/build/avalanchego", "--network-id=mainnet" ]
        resources:
          requests:
            memory: "4000Mi"
            cpu: "1"
          limits:
            memory: "4200Mi"
            cpu: "2"
        volumeMounts:
        - mountPath: /root
          name: example-volume
          readOnly: false
        ports:
        - containerPort: 9650
      volumes:
      - name: example-volume
        hostPath:
          path: /home # directory location on host
          type: Directory # this field is optional